### PR TITLE
Attackspeed

### PR DESCRIPTION
**Pull request by kkira07**
Units now have an attackcooldown variable, this determines their attack frequency. The attackOrDefend method gets the leftover time (atctime, deftime) from the last round of battle as patameter, then decides which character is the next attacker based on which of them had less remaining time.
The project now has doxygen documentation as well, which contains the class, the data in the class and the methods and functions along with their parameters.

### CODE REVIEW

**Review by vizvezetek — COMMENTED** [review]
A kód és a kommentezés rendben van. A github pagest be kell állítani az adott branch-re. (issue)
Ha ez megvan akkor tedd bele a readme-be és taggelj.

**Comment by kkira07** [comment]
@vizvezetek Megvan, link a readme-ben.

**Review by vizvezetek — APPROVED** [review]

**Comment by vizvezetek** [comment]
@hegyhati

**Comment by hegyhati** [comment]
access granted.

**Pull request merged**
